// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'property_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Property _$PropertyFromJson(Map<String, dynamic> json) => Property(
      id: json['id'] as String,
      description: json['description'] as String?,
      address: json['address'] as String,
      area: json['area'] as String,
      city: json['city'] as String,
      state: json['state'] as String?,
      latitude: (json['latitude'] as num?)?.toDouble(),
      longitude: (json['longitude'] as num?)?.toDouble(),
      agreementFee: (json['agreement_fee'] as num?)?.toDouble(),
      cautionFee: (json['caution_fee'] as num?)?.toDouble(),
      rentAmount: (json['rent_amount'] as num?)?.toDouble(),
      bedrooms: (json['bedrooms'] as num?)?.toInt(),
      bathrooms: (json['bathrooms'] as num?)?.toInt(),
      categoryId: json['category_id'] as String?,
      gallery:
          (json['gallery'] as List<dynamic>?)?.map((e) => e as String).toList(),
      coverImage: json['cover_image'] as String?,
      isAvailable: json['is_available'] as bool?,
      isVerified: json['is_verified'] as bool?,
      isFeatured: json['is_featured'] as bool?,
      featuredUntil:
          const CustomDateTimeConverter().fromJson(json['featured_until']),
      featuredPriority: (json['featured_priority'] as num?)?.toInt(),
      deleted: json['deleted'] as bool? ?? false,
      createdAt: const CustomDateTimeConverter().fromJson(json['created_at']),
      updatedAt: const CustomDateTimeConverter().fromJson(json['updated_at']),
      closestLandmark: json['closest_landmark'] as String?,
      furnished: json['furnished'] as String?,
      furnishingDetails: json['furnishing_details'] as String?,
      flagged: json['flagged'] as bool?,
      floorsNo: (json['floors_no'] as num?)?.toInt(),
      hasParking: json['has_parking'] as bool?,
      hasWaterHeater: json['has_water_heater'] as bool?,
      accessibilityFeatures: json['accessibility_features'] as String?,
      amenities: json['amenities'] as Map<String, dynamic>?,
      availableFrom:
          const CustomDateTimeConverter().fromJson(json['available_from']),
      rating: (json['rating'] as num?)?.toDouble(),
      reviewCount: (json['reviewCount'] as num?)?.toInt(),
      name: json['name'] as String?,
      landlordId: json['landlord_id'] as String?,
      kitchens: (json['kitchens'] as num?)?.toInt(),
      toilets: (json['toilets'] as num?)?.toInt(),
      listingType: json['listing_type'],
      status: json['status'],
      street: json['street'],
      sizeSqft: (json['size_sqft'] as num?)?.toDouble(),
      yearBuilt: (json['year_built'] as num?)?.toInt(),
      zipcode: json['zipcode'],
      parkingType: json['parking_type'],
      parkingSpaces: (json['parking_spaces'] as num?)?.toInt(),
      parkingSecurity: json['parking_security'],
      paymentStructure: json['payment_structure'],
      minimumLeaseDuration: json['minimum_lease_duration'],
      securityFeatures: (json['security_features'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      neighborhoodSecurity: json['neighborhood_security'],
      verificationStatus: json['verification_status'],
      videoTour: json['video_tour'],
      waterSource: json['water_source'],
      matchReason: json['match_reason'],
      recommendationScore: (json['recommendation_score'] as num?)?.toDouble(),
      tenantId: json['tenant_id'] as String?,
    );

Map<String, dynamic> _$PropertyToJson(Property instance) => <String, dynamic>{
      'id': instance.id,
      'description': instance.description,
      'address': instance.address,
      'area': instance.area,
      'city': instance.city,
      'state': instance.state,
      'latitude': instance.latitude,
      'longitude': instance.longitude,
      'agreement_fee': instance.agreementFee,
      'caution_fee': instance.cautionFee,
      'rent_amount': instance.rentAmount,
      'bedrooms': instance.bedrooms,
      'bathrooms': instance.bathrooms,
      'category_id': instance.categoryId,
      'gallery': instance.gallery,
      'cover_image': instance.coverImage,
      'is_available': instance.isAvailable,
      'is_verified': instance.isVerified,
      'is_featured': instance.isFeatured,
      'featured_until':
          const CustomDateTimeConverter().toJson(instance.featuredUntil),
      'featured_priority': instance.featuredPriority,
      'deleted': instance.deleted,
      'created_at': const CustomDateTimeConverter().toJson(instance.createdAt),
      'updated_at': const CustomDateTimeConverter().toJson(instance.updatedAt),
      'closest_landmark': instance.closestLandmark,
      'furnished': instance.furnished,
      'furnishing_details': instance.furnishingDetails,
      'flagged': instance.flagged,
      'floors_no': instance.floorsNo,
      'has_parking': instance.hasParking,
      'has_water_heater': instance.hasWaterHeater,
      'accessibility_features': instance.accessibilityFeatures,
      'amenities': instance.amenities,
      'available_from':
          const CustomDateTimeConverter().toJson(instance.availableFrom),
      'rating': instance.rating,
      'reviewCount': instance.reviewCount,
      'name': instance.name,
      'landlord_id': instance.landlordId,
      'kitchens': instance.kitchens,
      'toilets': instance.toilets,
      'listing_type': instance.listingType,
      'status': instance.status,
      'street': instance.street,
      'size_sqft': instance.sizeSqft,
      'year_built': instance.yearBuilt,
      'zipcode': instance.zipcode,
      'parking_type': instance.parkingType,
      'parking_spaces': instance.parkingSpaces,
      'parking_security': instance.parkingSecurity,
      'payment_structure': instance.paymentStructure,
      'minimum_lease_duration': instance.minimumLeaseDuration,
      'security_features': instance.securityFeatures,
      'neighborhood_security': instance.neighborhoodSecurity,
      'verification_status': instance.verificationStatus,
      'video_tour': instance.videoTour,
      'water_source': instance.waterSource,
      'match_reason': instance.matchReason,
      'recommendation_score': instance.recommendationScore,
      'tenant_id': instance.tenantId,
    };
