"""added some fields to the applications model


Revision ID: 08dd7d4cd0c9
Revises: 1e7b9d39f060
Create Date: 2025-10-01 14:15:10.936629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08dd7d4cd0c9'
down_revision = '1e7b9d39f060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('message', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('tour_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tour_confirmed', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('preferred_move_in', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('documents_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_column('documents_url')
        batch_op.drop_column('preferred_move_in')
        batch_op.drop_column('tour_confirmed')
        batch_op.drop_column('tour_date')
        batch_op.drop_column('message')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
