"""added onboarded field to the user db

Revision ID: 0f0495a6496f
Revises: 9078bf059630
Create Date: 2026-01-15 08:47:07.532683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f0495a6496f'
down_revision = '9078bf059630'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('onboarding_step', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_onboarded', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('landlord_info', schema=None) as batch_op:
        batch_op.drop_column('is_onboarded')
        batch_op.drop_column('onboarding_step')

    # ### end Alembic commands ###
