"""Added applicant_id to the application model


Revision ID: 133f34977da0
Revises: 5f3118a7c5be
Create Date: 2025-10-16 09:39:53.125288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '133f34977da0'
down_revision = '5f3118a7c5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('applicant_id', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['applicant_id'], ['id'])

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_properties_status'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_properties_status'), ['status'], unique=False)

    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('applicant_id')

    # ### end Alembic commands ###
