"""Updated the id lenght

Revision ID: 16402e9f239c
Revises: 286723a959ca
Create Date: 2025-07-13 15:26:49.449263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16402e9f239c'
down_revision = '286723a959ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('preferred_parking_space',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.alter_column('preferred_parking_space',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
