"""Added some moe fields to the user model

Revision ID: 1e7b9d39f060
Revises: 95373feb4d1a
Create Date: 2025-08-25 19:08:02.059635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7b9d39f060'
down_revision = '95373feb4d1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('verified', sa.String(length=20), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annual_income', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('screening_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_screened', sa.DateTime(), nullable=True))
        batch_op.alter_column('monthly_income',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=15, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('monthly_income',
               existing_type=sa.Numeric(precision=15, scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.drop_column('last_screened')
        batch_op.drop_column('screening_status')
        batch_op.drop_column('annual_income')

    op.drop_table('documents')
    # ### end Alembic commands ###
