"""added some models to the backend



Revision ID: 38401ed39696
Revises: 4417f7f3d4ee
Create Date: 2025-10-16 08:16:34.387474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38401ed39696'
down_revision = '4417f7f3d4ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('landlord_id', sa.String(length=20), nullable=False),
    sa.Column('report_type', sa.Enum('FINANCIAL', 'OCCUPANCY', 'TENANT', 'TRANSACTION', 'PROPERTY', 'MAINTENANCE', name='reporttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'GENERATING', 'COMPLETED', 'FAILED', name='reportstatus'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date_range_start', sa.DateTime(), nullable=False),
    sa.Column('date_range_end', sa.DateTime(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_format', sa.String(length=10), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspections',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.String(length=20), nullable=False),
    sa.Column('landlord_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=20), nullable=True),
    sa.Column('inspection_type', sa.Enum('MOVE_IN', 'MOVE_OUT', 'ROUTINE', 'MAINTENANCE', name='inspectiontype'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='inspectionstatus'), nullable=False),
    sa.Column('inspector_name', sa.String(length=200), nullable=True),
    sa.Column('scheduled_date', sa.DateTime(), nullable=False),
    sa.Column('scheduled_time', sa.String(length=10), nullable=False),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('findings', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_requests',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.String(length=20), nullable=False),
    sa.Column('landlord_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=20), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='maintenancepriority'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='maintenancestatus'), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('cost', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_requests')
    op.drop_table('inspections')
    op.drop_table('reports')
    # ### end Alembic commands ###
