"""updated the user model

Revision ID: 4417f7f3d4ee
Revises: 1903c4000072
Create Date: 2025-10-14 23:00:59.054678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4417f7f3d4ee'
down_revision = '1903c4000072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agency_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('license_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('years_of_experience', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('specializations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('service_areas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('commission_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('agent_bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('professional_website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('linkedin_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('linkedin_url')
        batch_op.drop_column('professional_website')
        batch_op.drop_column('agent_bio')
        batch_op.drop_column('commission_rate')
        batch_op.drop_column('service_areas')
        batch_op.drop_column('specializations')
        batch_op.drop_column('years_of_experience')
        batch_op.drop_column('license_number')
        batch_op.drop_column('agency_name')

    # ### end Alembic commands ###
