"""Added 'failed_login_attempts' to user model

Revision ID: 53e7cf93623c
Revises: 968f8af00bb7
Create Date: 2025-08-24 12:05:47.040031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53e7cf93623c'
down_revision = '968f8af00bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_id', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_message_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'properties', ['property_id'], ['id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_size', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('message_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_edited', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('failed_login_attempts')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('edited_at')
        batch_op.drop_column('is_edited')
        batch_op.drop_column('is_read')
        batch_op.drop_column('message_metadata')
        batch_op.drop_column('file_type')
        batch_op.drop_column('file_size')
        batch_op.drop_column('file_name')
        batch_op.drop_column('message_type')

    with op.batch_alter_table('chat_rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('last_message_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('property_id')

    # ### end Alembic commands ###
