"""added status

Revision ID: 5f3118a7c5be
Revises: 38401ed39696
Create Date: 2025-10-16 09:02:50.744215

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5f3118a7c5be"
down_revision = "38401ed39696"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add status column as String with default value to handle existing rows
    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.String(length=20),
                nullable=False,
                server_default="available",
            )
        )

    # Create index on status for faster queries
    op.create_index("ix_properties_status", "properties", ["status"])

    # Drop tables if they exist (these will be recreated by another migration)
    op.execute("DROP TABLE IF EXISTS inspections CASCADE")
    op.execute("DROP TABLE IF EXISTS maintenance_requests CASCADE")
    op.execute("DROP TABLE IF EXISTS reports CASCADE")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index first
    op.drop_index("ix_properties_status", table_name="properties")

    with op.batch_alter_table("properties", schema=None) as batch_op:
        batch_op.drop_column("status")

    op.create_table(
        "reports",
        sa.Column("id", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "landlord_id", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "report_type",
            postgresql.ENUM(
                "FINANCIAL",
                "OCCUPANCY",
                "TENANT",
                "TRANSACTION",
                "PROPERTY",
                "MAINTENANCE",
                name="reporttype",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING", "GENERATING", "COMPLETED", "FAILED", name="reportstatus"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column(
            "date_range_start",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "date_range_end",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "parameters",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "file_path", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
        sa.Column(
            "file_format", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "generated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["landlord_id"], ["users.id"], name=op.f("reports_landlord_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("reports_pkey")),
    )
    op.create_table(
        "maintenance_requests",
        sa.Column("id", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "property_id", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "landlord_id", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "tenant_id", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("title", sa.VARCHAR(length=200), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "priority",
            postgresql.ENUM(
                "LOW", "MEDIUM", "HIGH", "URGENT", name="maintenancepriority"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="maintenancestatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "scheduled_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "completed_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("cost", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["landlord_id"],
            ["users.id"],
            name=op.f("maintenance_requests_landlord_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("maintenance_requests_property_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["users.id"],
            name=op.f("maintenance_requests_tenant_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("maintenance_requests_pkey")),
    )
    op.create_table(
        "inspections",
        sa.Column("id", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column(
            "property_id", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "landlord_id", sa.VARCHAR(length=20), autoincrement=False, nullable=False
        ),
        sa.Column(
            "tenant_id", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column(
            "inspection_type",
            postgresql.ENUM(
                "MOVE_IN", "MOVE_OUT", "ROUTINE", "MAINTENANCE", name="inspectiontype"
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "status",
            postgresql.ENUM(
                "SCHEDULED",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="inspectionstatus",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "inspector_name", sa.VARCHAR(length=200), autoincrement=False, nullable=True
        ),
        sa.Column(
            "scheduled_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "scheduled_time", sa.VARCHAR(length=10), autoincrement=False, nullable=False
        ),
        sa.Column(
            "completed_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("findings", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("notes", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["landlord_id"], ["users.id"], name=op.f("inspections_landlord_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["property_id"],
            ["properties.id"],
            name=op.f("inspections_property_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["users.id"], name=op.f("inspections_tenant_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("inspections_pkey")),
    )
    # ### end Alembic commands ###
