"""updated the application model

Revision ID: 732975c47b48
Revises: 9164ecdf2374
Create Date: 2025-12-27 19:00:10.738208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '732975c47b48'
down_revision = '9164ecdf2374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('number_of_occupants', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('move_in_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
        batch_op.drop_column('email')
        batch_op.drop_column('preferred_move_in')
        batch_op.drop_column('phone')
        batch_op.drop_column('first_name')
        batch_op.drop_column('documents_url')
        batch_op.drop_column('last_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('documents_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preferred_move_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.alter_column('message',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('move_in_date')
        batch_op.drop_column('number_of_occupants')
        batch_op.drop_column('employment_status')

    # ### end Alembic commands ###
