"""Added some fields to the user model

Revision ID: 83547203b90a
Revises: 53e7cf93623c
Create Date: 2025-08-24 17:43:00.658988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83547203b90a'
down_revision = '53e7cf93623c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_failed_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_successful_login', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_successful_login')
        batch_op.drop_column('last_failed_login')

    # ### end Alembic commands ###
