"""Removed rent or buy

Revision ID: 876c190e1e74
Revises: c87c6ab0baee
Create Date: 2025-07-13 15:18:49.413228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876c190e1e74'
down_revision = 'c87c6ab0baee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_column('rent_or_buy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rent_or_buy', sa.VARCHAR(length=10), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
