"""Added decline reason in the screening model

Revision ID: 9078bf059630
Revises: 732975c47b48
Create Date: 2025-12-29 03:09:50.980462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9078bf059630'
down_revision = '732975c47b48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('decline_reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screenings', schema=None) as batch_op:
        batch_op.drop_column('decline_reason')

    # ### end Alembic commands ###
