"""Deleted the old database that is all

Revision ID: 9164ecdf2374
Revises: 
Create Date: 2025-12-26 20:31:23.644681

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9164ecdf2374'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('middleName', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('apartment_or_suite', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.Column('street_address', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_failed_login', sa.DateTime(), nullable=True),
    sa.Column('last_successful_login', sa.DateTime(), nullable=True),
    sa.Column('verification_token', sa.Text(), nullable=True),
    sa.Column('verification_code', sa.String(length=6), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('verified', sa.String(length=20), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landlord_info',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('business_registration_number', sa.String(length=100), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('years_as_landlord', sa.Integer(), nullable=True),
    sa.Column('property_ownership_docs', sa.JSON(), nullable=True),
    sa.Column('deed_or_title_document', sa.String(length=255), nullable=True),
    sa.Column('property_tax_receipt', sa.String(length=255), nullable=True),
    sa.Column('tax_identification_number', sa.String(length=50), nullable=True),
    sa.Column('tax_document', sa.String(length=255), nullable=True),
    sa.Column('utility_bill', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=15), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True),
    sa.Column('has_eviction_history', sa.Boolean(), nullable=True),
    sa.Column('eviction_history_details', sa.Text(), nullable=True),
    sa.Column('criminal_background', sa.Boolean(), nullable=True),
    sa.Column('criminal_background_details', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('previous_tenant_references', sa.JSON(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('verification_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verification_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('verification_reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verification_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landlord_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landlord_info_user_id'), ['user_id'], unique=True)

    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('listing_type', sa.String(length=30), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('toilets', sa.Integer(), nullable=True),
    sa.Column('kitchens', sa.Integer(), nullable=False),
    sa.Column('floors_no', sa.Integer(), nullable=False),
    sa.Column('size_sqft', sa.Float(), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=False),
    sa.Column('furnished', sa.String(length=50), nullable=False),
    sa.Column('furnishing_details', sa.JSON(), nullable=True),
    sa.Column('water_source', sa.String(length=20), nullable=False),
    sa.Column('has_water_heater', sa.Boolean(), nullable=True),
    sa.Column('security_features', sa.JSON(), nullable=True),
    sa.Column('neighborhood_security', sa.String(length=20), nullable=True),
    sa.Column('has_parking', sa.Boolean(), nullable=True),
    sa.Column('parking_type', sa.String(length=20), nullable=True),
    sa.Column('parking_security', sa.String(length=20), nullable=True),
    sa.Column('parking_spaces', sa.Integer(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('area', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zipcode', sa.Float(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('closest_landmark', sa.String(length=100), nullable=False),
    sa.Column('accessibility_features', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('payment_structure', sa.String(length=20), nullable=False),
    sa.Column('rent_amount', sa.Integer(), nullable=False),
    sa.Column('caution_fee', sa.Integer(), nullable=True),
    sa.Column('agreement_fee', sa.Integer(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=False),
    sa.Column('minimum_lease_duration', sa.String(length=20), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('gallery', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('video_tour', sa.String(length=255), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('featured_priority', sa.Integer(), nullable=True),
    sa.Column('featured_until', sa.DateTime(), nullable=True),
    sa.Column('landlord_id', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_drafts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('landlord_id', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parking_space', sa.Integer(), nullable=True),
    sa.Column('furnished', sa.String(length=50), nullable=True),
    sa.Column('pets', sa.String(length=50), nullable=True),
    sa.Column('kitchens', sa.Integer(), nullable=True),
    sa.Column('floors_no', sa.Integer(), nullable=True),
    sa.Column('size_sqft', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('gallery', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('closest_landmark', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('payment_structure', sa.String(length=20), nullable=True),
    sa.Column('rent_amount', sa.Integer(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('minimum_lease_duration', sa.String(length=20), nullable=True),
    sa.Column('service_charge', sa.Integer(), nullable=True),
    sa.Column('security_deposit', sa.Integer(), nullable=True),
    sa.Column('last_saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recent_activities',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('user_role', sa.String(length=20), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('activity_description', sa.Text(), nullable=False),
    sa.Column('related_entity_type', sa.String(length=50), nullable=True),
    sa.Column('related_entity_id', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('min_budget', sa.Float(), nullable=True),
    sa.Column('max_budget', sa.Float(), nullable=True),
    sa.Column('preferred_bedrooms', sa.Integer(), nullable=True),
    sa.Column('preferred_bathrooms', sa.Integer(), nullable=True),
    sa.Column('preferred_parking_space', sa.String(length=50), nullable=True),
    sa.Column('preferred_furnished', sa.String(length=50), nullable=True),
    sa.Column('preferred_pets', sa.String(length=50), nullable=True),
    sa.Column('preferred_kitchens', sa.Integer(), nullable=True),
    sa.Column('preferred_floors_no', sa.Integer(), nullable=True),
    sa.Column('preferred_size_sqft', sa.Float(), nullable=True),
    sa.Column('preferred_year_built', sa.Integer(), nullable=True),
    sa.Column('preferred_min_lease', sa.String(length=20), nullable=True),
    sa.Column('preferred_amenities', sa.JSON(), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('preferred_payment_frequency', sa.String(length=20), nullable=True),
    sa.Column('preferred_move_in_date', sa.Date(), nullable=True),
    sa.Column('property_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tenant_info',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('employment_start_date', sa.Date(), nullable=True),
    sa.Column('employment_duration', sa.String(length=50), nullable=True),
    sa.Column('income_source', sa.String(length=50), nullable=True),
    sa.Column('other_income_sources', sa.JSON(), nullable=True),
    sa.Column('total_monthly_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('has_bankruptcy_history', sa.Boolean(), nullable=True),
    sa.Column('bankruptcy_details', sa.Text(), nullable=True),
    sa.Column('previous_rental_history', sa.JSON(), nullable=True),
    sa.Column('current_landlord_reference', sa.String(length=255), nullable=True),
    sa.Column('previous_landlord_references', sa.JSON(), nullable=True),
    sa.Column('rental_payment_proof', sa.JSON(), nullable=True),
    sa.Column('tenant_background_check', sa.String(length=255), nullable=True),
    sa.Column('criminal_record_check', sa.String(length=255), nullable=True),
    sa.Column('has_evictions', sa.Boolean(), nullable=True),
    sa.Column('eviction_details', sa.Text(), nullable=True),
    sa.Column('has_lease_violations', sa.Boolean(), nullable=True),
    sa.Column('lease_violation_details', sa.Text(), nullable=True),
    sa.Column('personal_references', sa.JSON(), nullable=True),
    sa.Column('emergency_contact', sa.JSON(), nullable=True),
    sa.Column('has_pets', sa.Boolean(), nullable=True),
    sa.Column('pet_details', sa.JSON(), nullable=True),
    sa.Column('desired_move_in_date', sa.Date(), nullable=True),
    sa.Column('lease_duration_preference', sa.String(length=50), nullable=True),
    sa.Column('budget_range_min', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('budget_range_max', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('property_type_preferences', sa.JSON(), nullable=True),
    sa.Column('background_check_consent', sa.Boolean(), nullable=True),
    sa.Column('credit_check_consent', sa.Boolean(), nullable=True),
    sa.Column('data_processing_consent', sa.Boolean(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('verification_score', sa.Integer(), nullable=True),
    sa.Column('verification_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verification_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('verification_reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_info_user_id'), ['user_id'], unique=True)

    op.create_table('user_bank_details',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_holder_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('routing_number', sa.String(length=50), nullable=True),
    sa.Column('swift_code', sa.String(length=50), nullable=True),
    sa.Column('iban', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_document_url', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_bank_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_bank_details_user_id'), ['user_id'], unique=True)

    op.create_table('user_identity_documents',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_url', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_identity_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identity_documents_user_id'), ['user_id'], unique=False)

    op.create_table('user_insurance',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('insurance_type', sa.String(length=50), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('policy_url', sa.String(length=255), nullable=True),
    sa.Column('coverage_amount', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_insurance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_insurance_user_id'), ['user_id'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=True),
    sa.Column('applicant_id', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('tour_date', sa.DateTime(), nullable=True),
    sa.Column('tour_confirmed', sa.String(length=10), nullable=True),
    sa.Column('preferred_move_in', sa.DateTime(), nullable=True),
    sa.Column('documents_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=20), nullable=False),
    sa.Column('landlord_id', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leases',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('landlord_id', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('monthly_rent', sa.Integer(), nullable=False),
    sa.Column('security_deposit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('tenant_signed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_signature', sa.Text(), nullable=True),
    sa.Column('landlord_signed_at', sa.DateTime(), nullable=True),
    sa.Column('landlord_signature', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liked_properties',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('date_liked', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_seen', sa.SmallInteger(), nullable=True),
    sa.Column('recipient_id', sa.String(length=20), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_views',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('chat_room_id', sa.String(length=20), nullable=False),
    sa.Column('sender_id', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('screenings',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('application_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=20), nullable=False),
    sa.Column('landlord_id', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.String(length=20), nullable=False),
    sa.Column('bio_data', sa.JSON(), nullable=True),
    sa.Column('invitation_date', sa.DateTime(), nullable=True),
    sa.Column('screening_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('screening_id', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_purpose', sa.Enum('SCREENING', 'RENT', 'OTHER', name='paymentpurpose'), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('payments')
    op.drop_table('screenings')
    op.drop_table('messages')
    op.drop_table('reviews')
    op.drop_table('property_views')
    op.drop_table('notifications')
    op.drop_table('liked_properties')
    op.drop_table('leases')
    op.drop_table('chat_rooms')
    op.drop_table('applications')
    with op.batch_alter_table('user_insurance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_insurance_user_id'))

    op.drop_table('user_insurance')
    with op.batch_alter_table('user_identity_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_identity_documents_user_id'))

    op.drop_table('user_identity_documents')
    with op.batch_alter_table('user_bank_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_bank_details_user_id'))

    op.drop_table('user_bank_details')
    with op.batch_alter_table('tenant_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_info_user_id'))

    op.drop_table('tenant_info')
    op.drop_table('search_history')
    op.drop_table('recommendations')
    op.drop_table('recent_activities')
    op.drop_table('property_drafts')
    op.drop_table('properties')
    op.drop_table('notification_preferences')
    with op.batch_alter_table('landlord_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landlord_info_user_id'))

    op.drop_table('landlord_info')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
