"""Added some fields to the user model

Revision ID: 95373feb4d1a
Revises: 83547203b90a
Create Date: 2025-08-25 18:21:37.890509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95373feb4d1a'
down_revision = '83547203b90a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('state', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('employer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('monthly_income', sa.Float(precision=15, asdecimal=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('monthly_income')
        batch_op.drop_column('employer_name')
        batch_op.drop_column('state')
        batch_op.drop_column('street_address')

    # ### end Alembic commands ###
