"""Made some changes to the property model and created a new model

Revision ID: 968f8af00bb7
Revises: 16402e9f239c
Create Date: 2025-07-15 19:39:55.404863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '968f8af00bb7'
down_revision = '16402e9f239c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_views',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_type', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('toilets', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('furnishing_details', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('water_source', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('has_water_heater', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('security_features', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('neighborhood_security', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('has_parking', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('parking_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('parking_security', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('parking_spaces', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('amenities', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('accessibility_features', postgresql.ARRAY(sa.String()), nullable=True))
        batch_op.add_column(sa.Column('caution_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('agreement_fee', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('video_tour', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('zipcode',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
        batch_op.drop_column('date')
        batch_op.drop_column('parking_space')
        batch_op.drop_column('security_deposit')
        batch_op.drop_column('service_charge')
        batch_op.drop_column('pets')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pets', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('service_charge', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('security_deposit', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('parking_space', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.alter_column('zipcode',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('video_tour')
        batch_op.drop_column('agreement_fee')
        batch_op.drop_column('caution_fee')
        batch_op.drop_column('accessibility_features')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('area')
        batch_op.drop_column('amenities')
        batch_op.drop_column('parking_spaces')
        batch_op.drop_column('parking_security')
        batch_op.drop_column('parking_type')
        batch_op.drop_column('has_parking')
        batch_op.drop_column('neighborhood_security')
        batch_op.drop_column('security_features')
        batch_op.drop_column('has_water_heater')
        batch_op.drop_column('water_source')
        batch_op.drop_column('furnishing_details')
        batch_op.drop_column('toilets')
        batch_op.drop_column('listing_type')

    op.drop_table('property_views')
    # ### end Alembic commands ###
