"""broke down the user model to make it easier to handle huge rquest


Revision ID: 969d1e9c575a
Revises: 
Create Date: 2025-12-26 14:50:41.286948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '969d1e9c575a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlord_info',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('business_registration_number', sa.String(length=100), nullable=True),
    sa.Column('business_type', sa.String(length=50), nullable=True),
    sa.Column('years_as_landlord', sa.Integer(), nullable=True),
    sa.Column('property_ownership_docs', sa.JSON(), nullable=True),
    sa.Column('deed_or_title_document', sa.String(length=255), nullable=True),
    sa.Column('property_tax_receipt', sa.String(length=255), nullable=True),
    sa.Column('tax_identification_number', sa.String(length=50), nullable=True),
    sa.Column('tax_document', sa.String(length=255), nullable=True),
    sa.Column('utility_bill', sa.String(length=255), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=15), nullable=True),
    sa.Column('emergency_contact_relationship', sa.String(length=50), nullable=True),
    sa.Column('has_eviction_history', sa.Boolean(), nullable=True),
    sa.Column('eviction_history_details', sa.Text(), nullable=True),
    sa.Column('criminal_background', sa.Boolean(), nullable=True),
    sa.Column('criminal_background_details', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('previous_tenant_references', sa.JSON(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('verification_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verification_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('verification_reviewed_by', sa.String(length=50), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('verification_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('landlord_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_landlord_info_user_id'), ['user_id'], unique=True)

    op.create_table('tenant_info',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('employment_start_date', sa.Date(), nullable=True),
    sa.Column('employment_duration', sa.String(length=50), nullable=True),
    sa.Column('income_source', sa.String(length=50), nullable=True),
    sa.Column('other_income_sources', sa.JSON(), nullable=True),
    sa.Column('total_monthly_income', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('has_bankruptcy_history', sa.Boolean(), nullable=True),
    sa.Column('bankruptcy_details', sa.Text(), nullable=True),
    sa.Column('previous_rental_history', sa.JSON(), nullable=True),
    sa.Column('current_landlord_reference', sa.String(length=255), nullable=True),
    sa.Column('previous_landlord_references', sa.JSON(), nullable=True),
    sa.Column('rental_payment_proof', sa.JSON(), nullable=True),
    sa.Column('tenant_background_check', sa.String(length=255), nullable=True),
    sa.Column('criminal_record_check', sa.String(length=255), nullable=True),
    sa.Column('has_evictions', sa.Boolean(), nullable=True),
    sa.Column('eviction_details', sa.Text(), nullable=True),
    sa.Column('has_lease_violations', sa.Boolean(), nullable=True),
    sa.Column('lease_violation_details', sa.Text(), nullable=True),
    sa.Column('personal_references', sa.JSON(), nullable=True),
    sa.Column('emergency_contact', sa.JSON(), nullable=True),
    sa.Column('has_pets', sa.Boolean(), nullable=True),
    sa.Column('pet_details', sa.JSON(), nullable=True),
    sa.Column('desired_move_in_date', sa.Date(), nullable=True),
    sa.Column('lease_duration_preference', sa.String(length=50), nullable=True),
    sa.Column('budget_range_min', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('budget_range_max', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('property_type_preferences', sa.JSON(), nullable=True),
    sa.Column('background_check_consent', sa.Boolean(), nullable=True),
    sa.Column('credit_check_consent', sa.Boolean(), nullable=True),
    sa.Column('data_processing_consent', sa.Boolean(), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('verification_score', sa.Integer(), nullable=True),
    sa.Column('verification_submitted_at', sa.DateTime(), nullable=True),
    sa.Column('verification_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('verification_reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tenant_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenant_info_user_id'), ['user_id'], unique=True)

    op.create_table('user_bank_details',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('bank_name', sa.String(length=100), nullable=False),
    sa.Column('account_holder_name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('routing_number', sa.String(length=50), nullable=True),
    sa.Column('swift_code', sa.String(length=50), nullable=True),
    sa.Column('iban', sa.String(length=100), nullable=True),
    sa.Column('account_type', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verification_document_url', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_bank_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_bank_details_user_id'), ['user_id'], unique=True)

    op.create_table('user_identity_documents',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_url', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('verified_by', sa.String(length=50), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_identity_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identity_documents_user_id'), ['user_id'], unique=False)

    op.create_table('user_insurance',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('insurance_type', sa.String(length=50), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('policy_number', sa.String(length=100), nullable=False),
    sa.Column('policy_url', sa.String(length=255), nullable=True),
    sa.Column('coverage_amount', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_insurance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_insurance_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('tenant_verification_status')
        batch_op.drop_column('tenant_verification_notes')
        batch_op.drop_column('emergency_contact_relationship')
        batch_op.drop_column('current_landlord_reference')
        batch_op.drop_column('tenant_insurance_expiry')
        batch_op.drop_column('terms_accepted')
        batch_op.drop_column('tax_document')
        batch_op.drop_column('criminal_background')
        batch_op.drop_column('insurance_provider')
        batch_op.drop_column('landlord_verification_notes')
        batch_op.drop_column('desired_move_in_date')
        batch_op.drop_column('landlord_verification_attempts')
        batch_op.drop_column('tenant_insurance_provider')
        batch_op.drop_column('lease_duration_preference')
        batch_op.drop_column('budget_range_min')
        batch_op.drop_column('has_evictions')
        batch_op.drop_column('landlord_verification_submitted_at')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('criminal_background_details')
        batch_op.drop_column('tenant_verification_score')
        batch_op.drop_column('bank_verification_document')
        batch_op.drop_column('total_monthly_income')
        batch_op.drop_column('tenant_verification_reviewed_at')
        batch_op.drop_column('eviction_details')
        batch_op.drop_column('bank_routing_number')
        batch_op.drop_column('other_income_sources')
        batch_op.drop_column('identity_documents')
        batch_op.drop_column('is_landlord_onboarded')
        batch_op.drop_column('tenant_onboarding_step')
        batch_op.drop_column('insurance_expiry_date')
        batch_op.drop_column('data_processing_consent')
        batch_op.drop_column('previous_landlord_references')
        batch_op.drop_column('property_ownership_docs')
        batch_op.drop_column('previous_tenant_references')
        batch_op.drop_column('pet_details')
        batch_op.drop_column('landlord_verification_reviewed_by')
        batch_op.drop_column('previous_rental_history')
        batch_op.drop_column('lease_violation_details')
        batch_op.drop_column('income_source')
        batch_op.drop_column('business_type')
        batch_op.drop_column('eviction_history_details')
        batch_op.drop_column('employment_duration')
        batch_op.drop_column('deed_or_title_document')
        batch_op.drop_column('credit_check_consent')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('tenant_background_check')
        batch_op.drop_column('bankruptcy_details')
        batch_op.drop_column('landlord_verification_status')
        batch_op.drop_column('is_tenant_onboarded')
        batch_op.drop_column('tenant_insurance_policy_number')
        batch_op.drop_column('preferred_locations')
        batch_op.drop_column('utility_bill')
        batch_op.drop_column('property_type_preferences')
        batch_op.drop_column('references')
        batch_op.drop_column('employment_start_date')
        batch_op.drop_column('landlord_onboarding_step')
        batch_op.drop_column('rental_payment_proof')
        batch_op.drop_column('bank_account_number')
        batch_op.drop_column('tenant_verification_submitted_at')
        batch_op.drop_column('company_name')
        batch_op.drop_column('years_as_landlord')
        batch_op.drop_column('insurance_policy_number')
        batch_op.drop_column('tenant_insurance_document')
        batch_op.drop_column('criminal_record_check')
        batch_op.drop_column('tax_identification_number')
        batch_op.drop_column('tenant_verification_reviewed_by')
        batch_op.drop_column('landlord_verification_reviewed_at')
        batch_op.drop_column('budget_range_max')
        batch_op.drop_column('has_lease_violations')
        batch_op.drop_column('has_eviction_history')
        batch_op.drop_column('has_bankruptcy_history')
        batch_op.drop_column('account_holder_name')
        batch_op.drop_column('personal_references')
        batch_op.drop_column('background_check_consent')
        batch_op.drop_column('insurance_document')
        batch_op.drop_column('has_pets')
        batch_op.drop_column('business_registration_number')
        batch_op.drop_column('property_tax_receipt')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('emergency_contact_tenant')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact_tenant', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('property_tax_receipt', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('business_registration_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_pets', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('insurance_document', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('background_check_consent', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('personal_references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('account_holder_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_bankruptcy_history', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_eviction_history', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_lease_violations', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('budget_range_max', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('landlord_verification_reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_verification_reviewed_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tax_identification_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('criminal_record_check', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_insurance_document', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('insurance_policy_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('years_as_landlord', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('company_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_verification_submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bank_account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('rental_payment_proof', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('landlord_onboarding_step', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('employment_start_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('property_type_preferences', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('utility_bill', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('preferred_locations', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_insurance_policy_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_tenant_onboarded', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('landlord_verification_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bankruptcy_details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_background_check', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('credit_check_consent', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deed_or_title_document', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('employment_duration', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('eviction_history_details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('business_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('income_source', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lease_violation_details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('previous_rental_history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('landlord_verification_reviewed_by', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pet_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('previous_tenant_references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('property_ownership_docs', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('previous_landlord_references', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_processing_consent', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('insurance_expiry_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_onboarding_step', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_landlord_onboarded', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('identity_documents', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('other_income_sources', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bank_routing_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('eviction_details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_verification_reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_monthly_income', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bank_verification_document', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_verification_score', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('criminal_background_details', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('landlord_verification_submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_evictions', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('budget_range_min', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lease_duration_preference', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_insurance_provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('landlord_verification_attempts', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('desired_move_in_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('landlord_verification_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('insurance_provider', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('criminal_background', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tax_document', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('terms_accepted', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_insurance_expiry', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_landlord_reference', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_relationship', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_verification_notes', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenant_verification_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    with op.batch_alter_table('user_insurance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_insurance_user_id'))

    op.drop_table('user_insurance')
    with op.batch_alter_table('user_identity_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_identity_documents_user_id'))

    op.drop_table('user_identity_documents')
    with op.batch_alter_table('user_bank_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_bank_details_user_id'))

    op.drop_table('user_bank_details')
    with op.batch_alter_table('tenant_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenant_info_user_id'))

    op.drop_table('tenant_info')
    with op.batch_alter_table('landlord_info', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_landlord_info_user_id'))

    op.drop_table('landlord_info')
    # ### end Alembic commands ###
