"""Omo i did rubbish

Revision ID: c87c6ab0baee
Revises: 
Create Date: 2025-07-13 15:09:33.250025

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c87c6ab0baee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('firstName', sa.String(length=50), nullable=True),
    sa.Column('lastName', sa.String(length=50), nullable=True),
    sa.Column('middleName', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('apartment_or_suite', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=50), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('occupation', sa.String(length=100), nullable=True),
    sa.Column('employment_status', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('identity_card', sa.String(length=255), nullable=True),
    sa.Column('national_id_card', sa.String(length=255), nullable=True),
    sa.Column('verification_token', sa.Text(), nullable=True),
    sa.Column('verification_code', sa.String(length=6), nullable=True),
    sa.Column('is_onboarded', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=20), nullable=False),
    sa.Column('landlord_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('properties',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('landlord_id', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('bedrooms', sa.Integer(), nullable=False),
    sa.Column('bathrooms', sa.Integer(), nullable=False),
    sa.Column('parking_space', sa.Integer(), nullable=False),
    sa.Column('furnished', sa.String(length=50), nullable=False),
    sa.Column('pets', sa.String(length=50), nullable=False),
    sa.Column('kitchens', sa.Integer(), nullable=False),
    sa.Column('floors_no', sa.Integer(), nullable=False),
    sa.Column('size_sqft', sa.Float(), nullable=False),
    sa.Column('year_built', sa.Integer(), nullable=False),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('gallery', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('street', sa.String(length=100), nullable=False),
    sa.Column('closest_landmark', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('zipcode', sa.Integer(), nullable=False),
    sa.Column('payment_structure', sa.String(length=20), nullable=False),
    sa.Column('rent_amount', sa.Integer(), nullable=False),
    sa.Column('available_from', sa.Date(), nullable=False),
    sa.Column('minimum_lease_duration', sa.String(length=20), nullable=False),
    sa.Column('service_charge', sa.Integer(), nullable=False),
    sa.Column('security_deposit', sa.Integer(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=True),
    sa.Column('flagged', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('featured_priority', sa.Integer(), nullable=True),
    sa.Column('featured_until', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_drafts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('landlord_id', sa.String(length=50), nullable=False),
    sa.Column('category_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bedrooms', sa.Integer(), nullable=True),
    sa.Column('bathrooms', sa.Integer(), nullable=True),
    sa.Column('parking_space', sa.Integer(), nullable=True),
    sa.Column('furnished', sa.String(length=50), nullable=True),
    sa.Column('pets', sa.String(length=50), nullable=True),
    sa.Column('kitchens', sa.Integer(), nullable=True),
    sa.Column('floors_no', sa.Integer(), nullable=True),
    sa.Column('size_sqft', sa.Float(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('gallery', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('closest_landmark', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('payment_structure', sa.String(length=20), nullable=True),
    sa.Column('rent_amount', sa.Integer(), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('minimum_lease_duration', sa.String(length=20), nullable=True),
    sa.Column('service_charge', sa.Integer(), nullable=True),
    sa.Column('security_deposit', sa.Integer(), nullable=True),
    sa.Column('last_saved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recommendations',
    sa.Column('recommendation_id', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('rent_or_buy', sa.String(length=10), nullable=False),
    sa.Column('min_budget', sa.Float(), nullable=True),
    sa.Column('max_budget', sa.Float(), nullable=True),
    sa.Column('preferred_bedrooms', sa.Integer(), nullable=True),
    sa.Column('preferred_bathrooms', sa.Integer(), nullable=True),
    sa.Column('preferred_parking_space', sa.Integer(), nullable=True),
    sa.Column('preferred_furnished', sa.String(length=50), nullable=True),
    sa.Column('preferred_pets', sa.String(length=50), nullable=True),
    sa.Column('preferred_kitchens', sa.Integer(), nullable=True),
    sa.Column('preferred_floors_no', sa.Integer(), nullable=True),
    sa.Column('preferred_size_sqft', sa.Float(), nullable=True),
    sa.Column('preferred_year_built', sa.Integer(), nullable=True),
    sa.Column('preferred_min_lease', sa.String(length=20), nullable=True),
    sa.Column('preferred_amenities', sa.JSON(), nullable=True),
    sa.Column('preferred_locations', sa.JSON(), nullable=True),
    sa.Column('preferred_payment_frequency', sa.String(length=20), nullable=True),
    sa.Column('preferred_move_in_date', sa.Date(), nullable=True),
    sa.Column('property_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('recommendation_id')
    )
    op.create_table('search_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=False),
    sa.Column('search_query', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applications',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=True),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leases',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('landlord_id', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('monthly_rent', sa.Integer(), nullable=False),
    sa.Column('security_deposit', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('terms', sa.Text(), nullable=True),
    sa.Column('tenant_signed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_signature', sa.Text(), nullable=True),
    sa.Column('landlord_signed_at', sa.DateTime(), nullable=True),
    sa.Column('landlord_signature', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liked_properties',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('property_id', sa.String(length=50), nullable=False),
    sa.Column('date_liked', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('chat_room_id', sa.String(length=20), nullable=False),
    sa.Column('sender_id', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_seen', sa.SmallInteger(), nullable=True),
    sa.Column('recipient_id', sa.String(length=20), nullable=False),
    sa.Column('recipient_type', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.String(length=20), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=20), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('property_id', sa.String(length=20), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_table('screenings',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('application_id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=20), nullable=False),
    sa.Column('landlord_id', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.String(length=20), nullable=False),
    sa.Column('bio_data', sa.JSON(), nullable=True),
    sa.Column('invitation_date', sa.DateTime(), nullable=True),
    sa.Column('screening_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('screening_id', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['screening_id'], ['screenings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.String(length=20), nullable=False),
    sa.Column('property_id', sa.String(length=20), nullable=False),
    sa.Column('payment_id', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_purpose', sa.Enum('SCREENING', 'RENT', 'OTHER', name='paymentpurpose'), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('payments')
    op.drop_table('screenings')
    op.drop_table('reviews')
    op.drop_table('notifications')
    op.drop_table('messages')
    op.drop_table('liked_properties')
    op.drop_table('leases')
    op.drop_table('applications')
    op.drop_table('search_history')
    op.drop_table('recommendations')
    op.drop_table('property_drafts')
    op.drop_table('properties')
    op.drop_table('notification_preferences')
    op.drop_table('chat_rooms')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
